port:  5000
markdown: kramdown
encoding: utf-8
name: Code for Seoul
url: http://codeforseoul.codenamu.org
hacknight_img: dcamp.png
hacknight_time: 01:00PM
hacknight_date: 2014-07-12
hacknight_place: <a href="http://dcamp.kr">은행권청년창업재단 디캠프</a> 5층 세미나실 C
description: "Seoul civic group to build, share, and learn about civic tech."
navigation:
- text: Home
  url: /index.html
- text: Projects
  url: /projects.html
- text: People
  url: /people.html
- text: Events
  url: /events/index.html
  category: events

#- text: People
#  url: /people.html
# - text: Resources
#   url: /resources.html
