# Site settings
title: Code for Seoul Community
short_title: Code for Seoul Community
description: |
  코드포서울은 IT기술로 더 나은 서울을 만들기 위한 시민들의 자발적인 커뮤니티입니다.
keywords: |
  "civic hacking, 시빅해킹, code for seoul, 코드포서울, open data, 공공데이터, 데이터, data"
baseurl: ""
issues_url: https://github.com/codeforseoul/codeforseoul.github.io/issues
url: "http://codeforseoul.org/" # the base hostname & protocol for your site
contact: http://slack.codeforseoul.org
github_username: codeforseoul
github_repo: codeforseoul.github.io
# paypal: admin@okfn.org
# contact: https://discuss.okfn.org/c/openspending
gems:
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap

devs:
  -
      name: Hoony Jang
      github: hoony
  -
      name: Youngtaek Hong
      github: mozodev

contributors:

supporters:
  -
    name: Bitcoin Center Korea
    footer_logo: bitcoincenterkorea.png
  -
    name: COW & DOG
    footer_logo: cowndog.png

# googleanalytics: UA-8271754-63

markdown: kramdown

markdown_ext: "markdown,mkdown,mdown,mkdn,mkd,md"

permalink: pretty

related_projects:
  -
      name: 2014 Annual Report
      link: http://2014.codeforseoul.org
  -
      name: Where Does My Money Go?
      link: http://wheredoesmymoneygo.kr/
  -
      name: 지켜보고있다, 대한민국 재정
      link: http://transparency.codenamu.org/

collections:

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      edit: true
  -
    scope:
      path: "help"
    values:
      layout: "deprecated"
      section: "help"
  # -
  #   scope:
  #     path: "blog"
  #   values:
  #     layout: "post"
  #     section: "blog"
