# services

- name: "Where Does My Money Go?"
  indexpage: true
  website: "http://wheredoesmymoneygo.kr"
  github: "https://github.com/codeforseoul/wheredoesmymoneygo.kr"
  description: "내가 내는 세금이 어떻게 쓰이고 있는지 쉽게 볼 수 있는 서비스입니다. 영국에서 시작된 오픈소스 프로젝트로 내가 내는 소득세에 따라 어느 분야에 얼만큼 사용되고 있는지, 각 광역자치단체별로 특정 분야에 쓰이는 액수가 어떻게 다른지 확인할 수 있습니다."

- name: "Hangul Romanization"
  indexpage: true
  website: "https://github.com/codeforseoul/hangul"
  github: "https://github.com/codeforseoul/hangul"
  description: "강남스타일을 따라부르는 외국인들은 무엇을 보고 따라 읽을 수 있을까요? 한글의 로마자 표기법은 헷갈리기만 합니다. 강남? 갱냄? 이 문제를 해결하여 한국어를 정확히 발음할 수 있는 형태의 영어로 바꾸어드립니다."

- name: "알뜰 서울의 발견"
  indexpage: true
  website: "http://codeforseoul.org/FdAS"
  github: "https://github.com/codeforseoul/FdAS"
  description: "서울 시민이라면 이 정돈 알아아죠! 서울 시민이라면 누구나 서울시에서 받을 수 있는 모든 혜택들을 쉽게 찾아볼 수 있습니다. 나만이 알고 있는 서울시 복지 혜택을 다른 시민들에게 공유할 수도 있습니다."